# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-05 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180130_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='descriptions',
        ),
    ]
